### ISSUE TITLE
Getting segfault when running with boost 1.67

### ISSUE THREAD

**Issue by Kaju-Bubanja** [ethz-asl/ros_vrpn_client#57]
Running the file asl_vicon.launch with the prefix:  `launch-prefix="gdb -ex run --args"` I get following stacktrace: 

> 0x00007ffff5d07a0a in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> (gdb) where
> #0  0x00007ffff5d07a0a in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> #1  0x00007ffff642f2ae in std::_Rb_tree<void const*, std::pair<void const* const, boost::detail::tss_data_node>, std::_Select1st<std::pair<void const* const, boost::detail::tss_data_node> >, std::less<void const*>, std::allocator<std::pair<void const* const, boost::detail::tss_data_node> > >::_M_insert_unique(std::pair<void const* const, boost::detail::tss_data_node> const&) () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.67.0
> #2  0x00007ffff6426548 in boost::detail::add_new_tss_node(void const*, boost::shared_ptr<boost::detail::tss_cleanup_function>, void*) () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.67.0
> #3  0x00007ffff6426793 in boost::detail::set_tss_data(void const*, boost::shared_ptr<boost::detail::tss_cleanup_function>, void*, bool) () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.67.0
> #4  0x00007ffff78eb185 in ros::CallbackQueue::setupTLS() () from /opt/ros/kinetic/lib/libroscpp.so
> #5  0x00007ffff78edbe3 in ros::CallbackQueue::callAvailable(ros::WallDuration) () from /opt/ros/kinetic/lib/libroscpp.so
> #6  0x00007ffff792f9e4 in ros::internalCallbackQueueThreadFunc() () from /opt/ros/kinetic/lib/libroscpp.so
> #7  0x00007ffff6424eed in thread_proxy () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.67.0
> #8  0x00007ffff6e7b6ba in start_thread (arg=0x7fffee0a5700) at pthread_create.c:333
> #9  0x00007ffff548141d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

I'm fairly certain it has something to do with the boost update, since it broke a few other asl packages. If somebody has an idea it would be appreciated.

**Comment by Kaju-Bubanja** [comment]
After spending a day trying to hunt this down with valgrind I just resorted to installing boost 1.58 again. I guess kinetic is not meant to be used with 1.67.
